name: Build & Release Mebo Control App

on:
  push:
    tags:
      - "v*"   # Triggers only when you push a version tag like v1.0.0

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      # Package portable builds
      - name: Zip Windows portable build
        if: matrix.os == 'windows-latest'
        run: |
          cd dist
          powershell Compress-Archive -Path "Mebo Control.exe" -DestinationPath "MeboControl-Windows.zip"

      - name: Zip Linux portable build
        if: matrix.os == 'ubuntu-latest'
        run: |
          cd dist
          zip -r MeboControl-Linux.zip *.AppImage

      - name: Zip macOS build
        if: matrix.os == 'macos-latest'
        run: |
          cd dist
          zip -r MeboControl-Mac.zip *.dmg

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: mebo-control-${{ matrix.os }}
          path: dist/*.zip

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          path: ./artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
