name: Build Windows Portable App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build Windows Portable
        run: npm run build

      - name: Upload Windows Portable Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MeboControl-Windows
          path: dist/*.exe
