name: Build Desktop App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # No npm install needed since node_modules is committed!
      - name: Verify package.json + node_modules
        run: |
          echo "Checking repo contents..."
          ls -la

      - name: Build app
        run: npm run build

      - name: Archive Linux AppImage
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: MeboControl-Linux
          path: dist/*.AppImage

      - name: Archive Windows Portable
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: MeboControl-Windows
          path: dist/*.exe
