name: Build Desktop App

on:
  workflow_dispatch:   # manual run button in Actions tab
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            build: win
            artifact: Windows-Installer
          - os: macos-latest
            build: mac
            artifact: MacOS-Installer
          - os: ubuntu-latest
            build: linux
            artifact: Linux-Installer

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: Package app
        run: npx electron-builder --${{ matrix.build }} --publish never

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.artifact }}
          path: dist/**
