name: Build Desktop App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            os_name: Linux
          - os: windows-latest
            os_name: Windows
          - os: macos-latest
            os_name: Mac

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build
        env:
          GH_TOKEN: ""   # prevents publish errors

      - name: Package zip
        run: |
          cd dist
          zip -r ../MeboControl-${{ matrix.os_name }}.zip .
          cd ..

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MeboControl-${{ matrix.os_name }}
          path: MeboControl-${{ matrix.os_name }}.zip
