name: Build Desktop

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: Upload Linux AppImage
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v3
        with:
          name: MeboControl-Linux
          path: dist/*.AppImage

      - name: Upload macOS DMG
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v3
        with:
          name: MeboControl-macOS
          path: dist/*.dmg

      - name: Upload Windows Portable EXE
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v3
        with:
          name: MeboControl-Windows
          path: dist/*.exe
